services:
  server:
    container_name: css
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RCON_PASSWORD=mypass
      - SERVER_HOSTNAME="My Server"
    ports:
      - "27005:27005/udp"
      - "27015:27015"
      - "27015:27015/udp"
    volumes:
      - ./cfg:/home/steam/server/cstrike/cfg
      - ./belair_map/:/home/steam/belair_map
 