services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RCON_PASSWORD=${RCON_PASSWORD}
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
    ports:
      - "27005:27005/udp"
      - "27015:27015"
      - "27015:27015/udp"
    volumes:
      - ./cfg:/home/steam/server/cstrike/cfg
      - ./belair_map/:/home/steam/belair_map
